# Introducción a Python y Notebooks
### Autor: Ianpaul Maroli Fematt De La Garza 
## Modelos de Analitica Predictiva 

# 1. Bienvenida

¡Hola! Vamos a aprender los fundamentos de Python y Notebooks.

### Ejeución de Código en celda
- Presionando Shift + Enter se logra esto, o dando click en el botón de ejecución.
- Para agregar un comentario en código, conocido como 'inline comment', sólo basta con agregar un símbolo de gato "#" al inicio.

In [16]:
# Esto es un comentario, no afecta para nada el codigo.

print  ("sup, whats sup with it, vanilla face")

sup, whats sup with it, vanilla face


# 2. Tipos de datos básicos en Python.
En este punto asignaremos un valor a una variable, cuando utilizamos el signo de igual "=" una vez, se asigna un valor (no significa igualdad), y lo que este del lado izquierdo puede llevar el nombre que el desarrollador del código deseé.

In [17]:
# String (str)

nombre= "Ianpaul"
print("whats sup with it, vanilla face:", nombre)

whats sup with it, vanilla face: Ianpaul


In [18]:
# Números enteros (int)

edad = 21

print ("mi edad es:", edad)

mi edad es: 21


In [19]:
# Números flotantes o decimales (float)
altura= 176 
print("Mi estatura es:", altura)

Mi estatura es: 176


In [20]:
# Booleanos (bool), refiere a True/False ó 0/1.
estudiante = True

print ("soy alumno")

soy alumno


# 3. Estructuras de Datos básicos.

In [21]:
# Listas
frutas = {"manzanas", "banana", "cereza"}
print ("listas de frutas", frutas)

listas de frutas {'manzanas', 'banana', 'cereza'}


In [22]:
# Diccionarios (normalmente siguen el formato Key/Value)
persona = {
    "nombre": "Ianpaul",
    "edad": 21,
    "ciudad": "Monterrey",
    "guapo": "si"
}

print ("Informacion de la persona", persona)

Informacion de la persona {'nombre': 'Ianpaul', 'edad': 21, 'ciudad': 'Monterrey', 'guapo': 'si'}


In [23]:
# Otra manera de crear un diccionario
persona2 = dict(

    nombre = "Ianpaul",
    edad = 21,
    ciudad = "Monterrey",
    guapo = "si"
    
)

print("informacion de la persona", persona2)

informacion de la persona {'nombre': 'Ianpaul', 'edad': 21, 'ciudad': 'Monterrey', 'guapo': 'si'}


# 4. Estructuras de control

In [24]:
"""
Condicionales 'if statements'
Los principales signos comparativos son:
Menor que <
Mayor que >
Igual que ==
Menor igual <=
Mayor igual >=
"""
if edad >=18:
    print ("Eres mayor de edad")
else :
    print ("Eres mayor de edad")

Eres mayor de edad


In [25]:
# Otras formas de 'validar' información de un objeto con estructura de datos
# Ejemplo de listas.

if "manzana" in frutas:
    print ("si, la manzana esta en la lista")
else:
    print ("no esta en la lista")
    

no esta en la lista


In [26]:
# Bucles
# Ejemplo de un rango a con una lista hecha a mano.

for i in [0 , 1 , 2 , 3 , 4 , 5]:
    print(i)

0
1
2
3
4
5


In [ ]:
"""
Ejemplo de un bucle utilizando función range()
  Nota: En Python, los índices comienzan en 0 y la función range() excluye el valor final.
  Esto es importante tener en cuenta al trabajar con bucles y acceso a elementos en listas o arrays.
  Python sigue la convención de la notación de intervalos en matemáticas y ciencias de la computación [inicio, fin)
"""

for i in range (6):
    print(i)

'\nEjemplo de un bucle utilizando función range()\n  Nota: En Python, los índices comienzan en 0 y la función range() excluye el valor final.\n  Esto es importante tener en cuenta al trabajar con bucles y acceso a elementos en listas o arrays.\n  Python sigue la convención de la notación de intervalos en matemáticas y ciencias de la computación [inicio, fin)\n'

In [37]:
# Ejemplo con lista

for f in frutas:
    print (f)

manzanas
banana
cereza


In [46]:
# Ejemplo combinado
# combinaremos una condicional con un bucle y utilizaremos un "format string" y variables.

fruta_favorita = "manzana"

for fruta in frutas:
    if fruta == fruta_favorita:
        print(f"{fruta} es mi fruta favorita")

    else:
        print (f"la {fruta} no es mi fruta favorita")

la manzanas no es mi fruta favorita
la banana no es mi fruta favorita
la cereza no es mi fruta favorita


# 5. Introducción a Librerías.

### Fundamentos de Programación
1.  **Variable**: Un nombre que se asigna a un valor en un programa. Las
variables pueden almacenar diferentes tipos de datos, como números, texto o estructuras de datos más complejas.
  - `nombre = 'Jorge'`

2.  **Función**: Un bloque de código que realiza una tarea específica y puede ser reutilizado en diferentes partes del programa. Las funciones pueden recibir argumentos y devolver valores.
  - `print()`

3.  **Clase**: Una plantilla para crear objetos que define propiedades y comportamientos. Las clases son fundamentales en la programación orientada a objetos y permiten la creación de objetos personalizados.
  - `str()`, contiene métodos como `.upper()` y `.lower()`
  ```
  nombre = str('Jorge')
  print(nombre.lower())
  ```
  `[out]: 'jorge'`

4.  **Método**: Una función que se define dentro de una clase y se utiliza para realizar operaciones en objetos de esa clase. Los métodos pueden acceder y modificar los atributos de un objeto.
  - `.append()` de la clase `list` que agrega un elemento al final de una lista
    ```
    lista = ['Jorge', 'Ramírez']
    lista.append('García')
    print(lista)
    ```
    `[out]: ['Jorge', 'Ramírez', 'García']`

5.  **Librería** (o biblioteca): Un conjunto de código preescrito que proporciona funcionalidades específicas para ser utilizadas en programas. Las librerías suelen incluir funciones, clases y variables que pueden ser importadas y utilizadas en diferentes proyectos.
  - la librería `math` que proporciona funciones para cálculos matemáticos como `sin()` y `cos()`
  ```
  import math
  result = math.sin(10)
  print(result)
  ```
  `[out]: -0.5440211108893698`

6.  **Paquete**: Un conjunto de librerías o módulos relacionados que se distribuyen juntos. Los paquetes pueden incluir varias librerías, documentación y ejemplos de uso.
  - El paquete `numpy` proporciona herramientas para estructurar y analizar datos.
  ```
  import numpy
  x = np.array([1, 2, 3]) # Creación de un vector.
  suma = np.sum(x)
  print(suma)
  ```
  `[out]: 6`



## 5.1 Numpy

In [62]:
# Empezar a trabajar con Numpy, importar con alias 'np'
import numpy as np
# Crear un vector de una dimensión

vector=np.array(
    [10, 20, 30, 40, 50]
)

print(f"vector de una dimension: {vector}")


vector de una dimension: [10 20 30 40 50]


In [81]:
# Operaciones básicas con el vector
print(vector+5)
print(vector*2)
print(np.sqrt(vector))

[15 25 35 45 55]
[ 20  40  60  80 100]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [97]:
# Acceso a elementos
print(vector[0])
print(vector[-2:])

10
[40 50]


In [105]:
# Uso práctico en negocios: Generar un vector de precios de productos
precios = np.array(
    [299, 399, 499, 599, 699]
)
print(f"precios originales: {precios}")

precios originales: [299 399 499 599 699]


In [109]:
# Aplicar un descuento del 10% a todos los productos
precios_descuento = precios * 0.9 
print(precios_descuento)


[269.1 359.1 449.1 539.1 629.1]


## 5.2 Pandas

In [116]:
# Se importa con el alias 'pd'

import pandas as pd

# Crear un DataFrame con la información similar a la anterior.

df= pd.DataFrame(
    { 
        "producto" : ["teclado", "monitor", "celular", "tablet", "laptop"],
        "Precio": [299, 399, 499, 599, 699]
       
    }
)

# Mostrar el dataframe
display(df)


producto  Precio
0  teclado     299
1  monitor     399
2  celular     499
3   tablet     599
4   laptop     699

In [118]:
# Crear el mismo DataFrame a partir de vectores de Numpy

Precios = np.array(
    
      [299, 399, 499, 599, 699]
     
)
productos = np. array(
     ["teclado", "monitor", "celular", "tablet", "laptop"]
    
)

df=pd.DataFrame(
    {
        "producto": productos,
        "precio": precios,
        "precio con descuento": precios*0.9

    }
)

display (df)


producto  precio  precio con descuento
0  teclado     299                 269.1
1  monitor     399                 359.1
2  celular     499                 449.1
3   tablet     599                 539.1
4   laptop     699                 629.1